#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

from soma2bm_lib import convert_csv_to_bm_npz


def parse_args():
    parser = argparse.ArgumentParser(
        description="Batch convert SOMA/Bones CSV to BM npz using metadata manifest."
    )
    parser.add_argument("--csv_root", required=True, help="CSV root path")
    parser.add_argument(
        "--metadata_manifest",
        required=True,
        help="Path to filtered_csv_manifest.json generated by build_filtered_csv_manifest.py",
    )
    parser.add_argument("--output_root", required=True, help="Output root for npz files")
    parser.add_argument("--input_fps", type=int, default=120, help="Input csv fps")
    parser.add_argument("--output_fps", type=int, default=50, help="Output npz fps")
    parser.add_argument("--num_bodies", type=int, default=30, help="Body count for body_* arrays")
    parser.add_argument("--skip_existing", action="store_true", help="Skip existing npz files")
    parser.add_argument(
        "--assume_isaac_joint_order",
        action="store_true",
        help="Pass through to convert_csv_to_bm_npz (skip MJ->IL joint reorder).",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    csv_root = Path(args.csv_root)
    output_root = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    with open(args.metadata_manifest, encoding="utf-8") as f:
        manifest_payload = json.load(f)
    records = manifest_payload.get("records", manifest_payload if isinstance(manifest_payload, list) else [])

    converted = []
    failed = []
    skipped = []
    for item in records:
        rel = item["relative_csv_path"]
        src = csv_root / rel
        dst = output_root / Path(rel).with_suffix(".npz")
        if args.skip_existing and dst.exists():
            skipped.append({"relative_csv_path": rel, "output_npz": str(dst)})
            continue
        try:
            convert_csv_to_bm_npz(
                input_csv=str(src),
                output_npz=str(dst),
                input_fps=args.input_fps,
                output_fps=args.output_fps,
                num_bodies=args.num_bodies,
                apply_mujoco_csv_to_isaac_joint_reorder=not args.assume_isaac_joint_order,
            )
            converted.append({"relative_csv_path": rel, "output_npz": str(dst)})
        except Exception as e:  # noqa: BLE001
            failed.append({"relative_csv_path": rel, "error": str(e)})

    report = {
        "csv_root": str(csv_root.resolve()),
        "output_root": str(output_root.resolve()),
        "metadata_manifest": str(Path(args.metadata_manifest).resolve()),
        "total_records": len(records),
        "converted_count": len(converted),
        "failed_count": len(failed),
        "skipped_count": len(skipped),
        "converted": converted,
        "failed": failed,
        "skipped": skipped,
    }
    report_path = output_root / "conversion_report.json"
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"[OK] report: {report_path}")
    print(
        f"[INFO] total={len(records)} converted={len(converted)} "
        f"failed={len(failed)} skipped={len(skipped)}"
    )


if __name__ == "__main__":
    main()
